export const profileData = {
  name: "Mohammed Vepari",
  title: "Backend & Infrastructure Engineer",
  location: "Brampton, ON",
  phone: "(416) 277-4564",
  email: "mohammedvepari@mohammed-vepari.dev",
  githubUrl: "https://github.com/MohammedVep",
  linkedInUrl: "https://www.linkedin.com/in/mohammed-v-2094b222a/",
  resumeUrl: "/Mohammed's_Resume.pdf",
  degreeProofUrl: "/Mohammed_Vepari_BCS_Honours_Degree_Proof.pdf",
  netPulseLiveUrl: "https://netpulsemanage.dev",
  netPulseRepoUrl: "https://github.com/MohammedVep/NetPulse",
  sreDashboardUrl: "/sre-dashboard",
  aiSystemLiveUrl: "https://sharedaigateway.com",
  aiSystemRepoUrl: "https://github.com/MohammedVep/ai-system-shared-ai-platform",
  workAuthorization: "Legally authorized to work in Canada without employer sponsorship.",
  availability: "Available for on-site, hybrid, or remote roles (EST/EDT).",
  summary:
    "Honours Bachelor of Computer Science (2026) @ Algoma University•  GPA 3.7/4.0 • Architecting fault-tolerant, auto-scaling distributed systems using Java, Go, Node, Kubernetes, and AWS Terraform.",
} as const;
